### PR TITLE
Made compatible with no_std and no atomic ptr

### PR DESCRIPTION
**Pull request by BjornTheProgrammer**
This is in preparation for Burn's pull request [#2096](https://github.com/tracel-ai/burn/pull/2096).

Some tests should be added to ensure that this doesn't end up breaking in the future, I can do so, but I'm unfamiliar with the testing story here. It would just need to be built with the `thumbv6m-none-eabi` target

### CODE REVIEW

**Comment by antimora** [comment]
@BjornTheProgrammer FYI, it's sufficient to fix make this work with crates in this test: https://github.com/tracel-ai/burn/tree/main/crates/burn-no-std-tests

cubecl doesn't need to be no-std compatible.

**Comment by BjornTheProgrammer** [comment]
You're totally right, for whatever reason, during my testing on my local machine it broke without my version. I think I've found the issue though. Sorry for the inconvenience

**Comment by antimora** [comment]
@nathanielsimard can you please look into this? For some reason burn-common has dependency on cube.

**Review by nathanielsimard — COMMENTED** [review]
`cubecl-common` should actually be `no-std` when `std` isn't enabled. The current fix seems fine to me.

**Comment by BjornTheProgrammer** [comment]
> `cubecl-common` should actually be `no-std` when `std` isn't enabled. The current fix seems fine to me.

Is it fine for this to be merged then?

**Pull request merged**
